apiVersion: v1
kind: Pod
metadata:
  name: logger-pod
  namespace: logging-ns
spec:
  containers:
  - name: logger-container
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "while true; do echo $(date) | tee /dev/stderr; sleep 1; done"