apiVersion: v1
kind: ReplicationController
metadata: 
  name: hello-rc
spec: 
  replicas: 3
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-pod
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
